contrib/frontends/django/nntpchan/nntpchan/frontend/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ctl-(?P<page>[0-9]+)\.html$', views.modlog, name='old-modlog'),
    url(r'^mod/$', views.ModView.as_view(), name='mod'),
    url(r'^mod/keygen', views.keygen, name='keygen'),
    url(r'^mod/(?P<page>[0-9]+)$', views.modlog, name='mod-page'),
    url(r'^overchan\.(?P<name>[a-zA-Z0-9\.]+)-(?P<page>[0-9]+)\.html$', views.BoardView.as_view(), name='old-board'),
    url(r'^overchan\.(?P<name>[a-zA-Z0-9\.]+)/', views.BoardView.as_view(), name='board-alt'),
    url(r'^thread-(?P<op>[a-fA-F0-9\.]{40})\.html$', views.ThreadView.as_view(), name='old-thread'),
    url(r'^b/(?P<name>[a-zA-Z0-9\.]+[a-zA-Z0-9])/$', views.BoardView.as_view(), name='board-front'),
    url(r'^b/(?P<name>[a-zA-Z0-9\.]+[a-zA-Z0-9])/(?P<page>[0-9]+)/$', views.BoardView.as_view(), name='board'),
    url(r'^t/(?P<op>[a-fA-F0-9\.]{40})/$', views.ThreadView.as_view(), name='thread'),
    url(r'captcha.png', views.create_captcha, name='captcha'),
    url(r'^$', views.FrontPageView.as_view(), name='frontpage'),
]

contrib/frontends/django/nntpchan/nntpchan/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^webhook$', views.webhook),
    url(r'^nntpchan/', include('nntpchan.frontend.urls', namespace='frontend'), name='nntpchan')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns.append(url(r'', views.frontpage, name='frontpage'))

contrib/frontends/django/nntpchan/nntpchan/frontend/views.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.views import generic


from .models import Post, Newsgroup, ModPriv

from captcha.image import ImageCaptcha
from . import util

captcha = ImageCaptcha(fonts=settings.CAPTCHA_FONTS)


class Postable:
    """
    postable view
    checks captcha etc
    """

    def context_for_get(self, request, defaults):
        defaults['captcha'] = reverse('frontend:captcha')
        defaults['refresh_url'] = request.path
        return defaults

    def handle_post(self, request, **kwargs):
        """
        handle post request, implement in subclass
        """
        return None, 'handle_post() not implemented'

    def handle_mod(self, request):
        """
        handle moderation parameters
        """
        if 'modactions' in request.POST:
            actions = request.POST['modactions']
            if len(actions) > 0:
                body = ''
                for line in actions.split('\n'):
                    line = line.strip()
                    if len(line) > 0:
                        body += '{}\n'.format(line)
                key = None
                if 'secret' in request.POST:
                    key = request.POST['secret']
                _, err = util.createPost('ctl', '', {'message': body}, {}, key)
                return True, err
        return False, None
    
    def post(self, request, **kwargs):
        ctx = {
            'error' : 'invalid captcha',
            'only_mod': False
        }
        # bypass captcha for mod users
        mod = None
        if 'mod' in request.session:
            mod = request.session['mod']
        if mod is None:
            solution = request.session['captcha']
            if solution is not None:
                if 'captcha' in request.POST:
                    if request.POST['captcha'].lower() == solution.lower():
                        processed, err = self.handle_mod(request)
                        if processed:
                            ctx['error'] = err or 'report made'
                            ctx['msgid'] = ''
                        else:
                            ctx['msgid'], ctx['error'] = self.handle_post(request, **kwargs)
            request.session['captcha'] = ''
        else:
            # we have a mod session
            ctx['msgid'], ctx['error'] = self.handle_post(request, **kwargs)
            
        request.session.save()
        code = 201
        if ctx['error']:
            code = 200
        elif ctx['msgid']:
            ctx['refresh_url'] = reverse('frontend:thread', args=[util.hashid(ctx['msgid'])])
        return HttpResponse(content=render(request, 'frontend/postresult.html', ctx), status=code)

        
class BoardView(generic.View, Postable):
    template_name = 'frontend/board.html'
    context_object_name = 'threads'
    model = Post

    def handle_post(self, request, name):
        """
        make a new thread
        """
        name = 'overchan.{}'.format(name)
        if not util.newsgroup_valid(name):
            return None, "invalid newsgroup: {}".format(name)
        self.handle_mod(request)
        return util.createPost(name, None, request.POST, request.FILES)

    
    def get(self, request, name, page="0"):
        newsgroup = 'overchan.{}'.format(name)
        try:
            page = int(page or "0")
        except:
            page = 0
        if page < 0:
            page = 0
        try:
            group = Newsgroup.objects.get(name=newsgroup)
        except Newsgroup.DoesNotExist:
            raise Http404("no such board")
        else:
            begin = page * group.posts_per_page
            end = begin + group.posts_per_page - 1
            roots = self.model.objects.filter(newsgroup=group, reference='').order_by('-last_bumped')[begin:end]
            ctx = self.context_for_get(request, {'threads': roots, 'page': page, 'name': newsgroup, 'button': 'new thread'})
            if page < group.max_pages:
                ctx['nextpage'] = reverse('frontend:board', args=[name, page + 1])
            if page == 1:
                ctx['prevpage'] = reverse('frontend:board-front', args=[name])
            if page > 1:
                ctx['prevpage'] = reverse('frontend:board', args=[name, page - 1])
            return render(request, self.template_name, ctx)
        
class ThreadView(generic.View, Postable):
    template_name = 'frontend/thread.html'
    model = Post

    def handle_post(self, request, op):
        """
        make a new thread
        """
        post = get_object_or_404(self.model, posthash=op)
        name = post.newsgroup.name
        if not util.newsgroup_valid(name):
            return None, "invalid newsgroup: {}".format(name)
        return util.createPost(name, post.msgid, request.POST, request.FILES)

    
    def get(self, request, op):
        posts = get_object_or_404(self.model, posthash=op)
        ctx = self.context_for_get(request, {'op': posts, 'button': 'reply'})
        return render(request, self.template_name, ctx)
    
class FrontPageView(generic.View):
    template_name = 'frontend/frontpage.html'
    model = Post

    def get(self, request, truncate=5):
        if truncate <= 0:
            truncate = 5
        posts = self.model.objects.order_by('-posted')[:truncate]
        ctx = {'posts' : posts}
        return render(request, self.template_name, ctx)
    

class ModView(generic.View, Postable):

    def show_login(self, request):
        """
        handle login page
        """
        request.session['mod'] = None
        request.session.save()
        return render(request, 'frontend/modlogin.html')

    def logout(self, request):
        request.session['mod'] = None
        request.session.save()
        return render(request, 'frontend/redirect.html', { 'url' : reverse('frontend:mod')})

    def post(self, request):
        action = None
        if 'action' in request.POST:
            action = request.POST['action']
        mod = None
        msg = 'bad login'
        if 'mod' in request.session:
            mod = request.session['mod']
        if action == 'logout':
            return self.logout(request)
        if action == 'login' and 'secret' in request.POST and mod is None:
            # try login
            sk = request.POST['secret']
            pk = None
            try:
                pk = util.to_public(sk)
                print (pk)
            except:
                msg = 'bad key format'
            if pk is not None and ModPriv.has_access(ModPriv.LOWEST, pk):
                mod = request.session['mod'] = {'sk' : sk, 'pk' : pk}
                request.session.save()
                # login okay
                return render(request, 'frontend/redirect.html', {'url' : reverse('frontend:mod'), 'msg' : 'logged in'})
        if mod is None:
            # no mod session
            return render(request, 'frontend/redirect.html', {'url' : reverse('frontend:mod'), 'msg' : msg } )
        else:
            # do mod action
            return self.handle_mod_action(request, mod, action)

    def handle_mod_action(self, request, mod, action):
        msg = 'no action made'
        if action is not None:
            if action == 'delete':
                # handle bulk delete
                if 'posts' in request.POST:
                    body = '\ndelete '.join(request.POST['posts'].split())
                    sk = mod['sk']
                    _, err = util.createPost('ctl', '', {'message' : body }, {}, sk)
                    if err:
                        msg = 'error: {}'.format(err)
                    else:
                        msg = 'okay'
        
        return render(request, 'frontend/redirect.html', {'url' : reverse('frontend:mod'), 'msg' : msg} )
    
    def get(self, request):
        mod = None
        if 'mod' in request.session:
            mod = request.session['mod']
        if mod:
            return render(request, 'frontend/modpage.html', {'mod' : mod })
        else:
            return self.show_login(request)
        
        
def modlog(request, page=None):
    page = int(page or '0')
    ctx = {
        'page': page,
    }
    if page > 0:
        ctx['prevpage'] = reverse('frontend:modlog-page', args=[page - 1])

    group, _ = Newsgroup.objects.get_or_create(name='ctl')
    if page < group.max_pages:
        ctx['nextpage'] = reverse('frontend:modlog-page', args=[page + 1])
    begin = group.posts_per_page * page
    end = begin + group.posts_per_page - 1
    ctx['threads'] = Post.objects.filter(newsgroup='ctl').order_by('-last_bumped')[begin:end]
    return render(request, 'frontend/board.html', ctx)

def create_captcha(request):
    solution = util.randstr(7).lower()
    request.session['captcha'] = solution
    request.session.save()
    c = captcha.generate(solution)
    r =HttpResponse(c)
    r['Content-Type'] = 'image/png'
    return r

def keygen(request):
    """
    generate new keypair
    """
    ctx = {}
    ctx['sk'], ctx['pk'] = util.keygen()
    return render(request, 'frontend/keygen.html', ctx)

contrib/frontends/django/nntpchan/nntpchan/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt   

from .frontend.models import Post, Attachment, Newsgroup, ModPriv
from .frontend import util

from . import thumbnail

import email
import traceback
from datetime import datetime
import mimetypes
import os


def frontpage(request):
    """
    frontpage for entire webapp
    """
    return render(request, 'frontpage.html')

@csrf_exempt
def webhook(request):
    """
    endpoint for nntpchan daemon webhook
    """
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    try:
        msg = email.message_from_bytes(request.body)
        process_message(msg)
    except Exception as ex:
        traceback.print_exc()
        return JsonResponse({ 'error': '{}'.format(ex) })
    else:
        return JsonResponse({'posted': True})


        
    
def process_message(msg):

    newsgroup = msg.get('Newsgroups')

    if newsgroup is None:
        raise Exception("no newsgroup specified")
    
    if not util.newsgroup_valid(newsgroup):
        raise Exception("invalid newsgroup name")
    
    bump = True
    group, created = Newsgroup.objects.get_or_create(name=newsgroup)
    if created:
        group.save()
    if group.banned:
        raise Exception("newsgroup is banned")
        
    msgid = None
    for h in ('Message-ID', 'Message-Id', 'MessageId', 'MessageID'):
        if h in msg:
            msgid = msg[h]
            break
        # check for sage
    if 'X-Sage' in msg and msg['X-Sage'] == '1':
        bump = False
            
    if msgid is None:
        raise Exception("no message id specified")
    elif not util.msgid_valid(msgid):
        raise Exception("invalid message id format: {}".format(msgid))
        
    opmsgid = msgid
        
    h = util.hashid(msgid)
    atts = list()
    ref = msg['References'] or ''
    posted = util.time_int(email.utils.parsedate_to_datetime(msg['Date']))
    
    if len(ref) > 0:
        opmsgid = ref
    
    f = msg['From'] or 'anon <anon@anon>'
    name = email.utils.parseaddr(f)[0]
    post, created = Post.objects.get_or_create(defaults={
        'posthash': h,
        'reference': ref,
        'posted': posted,
        'last_bumped': 0,
        'name': name,
        'subject': msg["Subject"] or '',
        'newsgroup': group}, msgid=msgid)
    
    if not created:
        post.subject = msg["Subject"] or ''
        post.name = name
        post.posted = posted
    m = ''
        
    for part in msg.walk():
        ctype = part.get_content_type()
        print (ctype)
        if ctype.startswith("text/plain"):
            m += '{} '.format(part.get_payload(decode=True).decode('utf-8'))
        elif ctype.startswith("message/rfc822"):
            # signed message
            payload = part.get_payload()
            if payload is None:
                raise Exception('invalid signed message, no body')
            for inner in payload:
                if not util.verify_message(msg["X-Pubkey-Ed25519"], msg['X-Signature-Ed25519-Sha512'], inner.as_bytes()):
                    raise Exception('invalid signed message, signature failed')
                process_message(inner)
                print('processed inner')
        else:
            payload = part.get_payload(decode=True)
            if payload is None:
                continue
            filename = part.get_filename()
            mtype = part.get_content_type()
            ext = filename.split('.')[-1].lower()
            fh = util.hashfile(bytes(payload))
            fn = fh + '.' + ext
            fname = os.path.join(settings.MEDIA_ROOT, fn)
            if not os.path.exists(fname):
                with open(fname, 'wb') as f:
                    f.write(payload)
                    tname = os.path.join(settings.MEDIA_ROOT, 'thumb-{}.jpg'.format(fn))
                    placeholder = os.path.join(settings.ASSETS_ROOT, 'placeholder.jpg')
            if not os.path.exists(tname):
                thumbnail.generate(fname, tname, placeholder)
                    
            att = Attachment(filehash=fh)
            att.mimetype = mtype
            att.filename = filename
            att.save()
            atts.append(att)
    post.message = m
    post.save()

            
    for att in atts:
        if post.has_attachment(att.filehash):
            continue
        post.attachments.add(att)
        
            
    op, _ = Post.objects.get_or_create(defaults={
        'posthash': util.hashid(opmsgid),
        'reference': '',
        'posted': 0,
        'last_bumped': 0,
        'name': 'OP',
        'subject': 'OP Not Found',
        'newsgroup': group}, msgid=opmsgid)
    if bump:
        op.bump(post.posted)
        op.save()
        

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %} nntpchan {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="stylesheet" type="text/css" media="(max-width: 699px) and (min-width: 520px)" href="{% static 'narrow.css' %}" />
<!-- <link rel="stylesheet" type="text/css" media="screen and not (max-width: 420px)" href="{% static 'desktop.css'%}"  /> -->
    <script type="text/javascript" src="{% static 'hooks.js' %}"></script>
    <script type="text/javascript" src="{% static 'postform.js' %}"></script>
    <script type="text/javascript" src="{% static 'banners.js' %}"></script>
    <script type="text/javascript" src="{% static 'settings.js' %}"></script>
    <script type="text/javascript" src="{% static 'captcha.js' %}"></script>
    <script type="text/javascript" src="{% static 'cite.js' %}"></script>
    <script type="text/javascript" src="{% static 'censor.js' %}"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    <div id="wrapper">
      <div id="navbar">
        <div class="navbar left">
          {% block navbar_frontpage %}<div id="navbar_frontpage"><a href="{% url 'frontend:frontpage' %}">nntpchan</a></div> |{% endblock %}
          <div id="navbar_title">{% block navbar_title %}{% endblock %}</div>
          <div id="navbar_links">{% block navbar_links %}{% endblock %}</div>
        </div>
        <div class="navbar right">
          <div>{% block navbar_left %}| <a href="#" onclick="nntpchan_toggle_settings_pane()">settings</a>{% endblock %}</div>
        </div>
      </div>
      <div id="content">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <hr/>
    <center>
      <footer>
        <p>All posts on this site are the responsibility of the individual poster and not the administration, pursuant to 47 U.S.C. § 230.</p>
        <p>To make a DMCA request or report illegal content, please contact the administration</p>
      </footer>
    </center>
    <script>
      ready();
    </script>
  </body>
</html>

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/board.html
{% extends "frontend/base.html" %}
{% load chanup %}
{% block title %} {{name}} page {{page}} {% endblock %}
{% block navbar_links %}
  {% if prevpage %}
<span class="navbar_link"><a href="{{prevpage}}">previous page</a></span> 
  {% endif %}
{% if nextpage %}
  {% if prevpage %}|{% endif %}
<span class="navbar_link"><a href="{{nextpage}}">next page</a></span>
  {% endif %}
{% endblock %}
{% block content %}
{% if captcha %}
{% include "frontend/postform.html" %}
{% endif %}
{% for op in threads %}
<div id="{{op.posthash}}" class="thread">
  <div class="post op" data-msgid="{{op.msgid}}">
    <div class="post-header">
      <div class="post-reply"><a href="{{op.get_absolute_url}}">[reply]</a></div>
      <div class="post-cite"><a onclick="board_citepost('{{op.posthash}}')" href="#{{op.posthash}}">&gt;&gt;{{op.shorthash}}</a></div>
      <div class="post-info">
        <div class="post-report">
        <label for="report_{{op.posthash}}">[x]</label>
          <input type="checkbox" id="report_{{op.posthash}}">
          <div style="display: none;" onclick="nntpchan_report_thread('{{op.posthash}}')">
            <div class="mod-delete">
              [delete thread]
            </div>
          </div>
        </div>
        <div class="post-name">{{op.name}}</div>
        <div class="post-subject">{{op.subject}}</div>
        <div class="post-date">{{op.postdate|date}}</div>
      </div>
    </div>
    <div class="attachments">
      {% for a in op.attachments.all %}
      <a target="_blank" href="{{a.source}}"><img class="thumb" src="{{a.thumb}}"></img></a>
      {% endfor %}
    </div>
    <pre class="postbody">{{op.message|truncate|memepost}}</pre>
  </div>
  {% for reply in op.get_board_replies %}
  <div class="post reply" data-msgid="{{reply.msgid}}" id="{{reply.posthash}}">
    <div class="post-header">
      <div class="post-reply"><a href="{{reply.get_absolute_url}}">[reply]</a></div>
      <div class="post-cite"><a onclick="board_citepost('{{reply.posthash}}')" href="#{{reply.posthash}}">&gt;&gt;{{reply.shorthash}}</a></div>
      <div class="post-info">
        <div class="post-report">
        <label for="report_{{reply.posthash}}">[x]</label>
          <input type="checkbox" id="report_{{reply.posthash}}">
          <div style="display: none;" onclick="nntpchan_report('{{reply.msgid}}')">
            <div class="mod-delete">
              [delete post]
            </div>
          </div>
        </div>        <div class="post-name">{{reply.name}}</div>
        <div class="post-subject">{{reply.subject}}</div>
        <div class="post-date">{{reply.postdate|date}}</div>
      </div>
    </div>
    <div class="attachments">
      {% for a in reply.attachments.all %}
      <a target="_blank" href="{{a.source}}"><img class="thumb" src="{{a.thumb}}"></img></a>
      {% endfor %}
    </div>
    <pre class="postbody">{{reply.message|truncate|memepost}}</pre>
  </div>
  {% endfor %}
</div>
<hr />
{% endfor %}
<div class="paginator">
  {% if prevpage %}
  <span class="paginator_item"><a href="{{prevpage}}">prev</a></span>
  {% endif %}
  {% if nextpage %}
  <span class="paginator_item"><a href="{{nextpage}}">next</a></span>
  {% endif %}
</div>
{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/frontpage.html
{% extends "frontend/base.html" %}
{% load chanup %}
{% block content %}
<div class="frontpage posts">
{% for post in posts %}
<div class="post">
  
  <div class="boardname"><a href="{{post.newsgroup.get_absolute_url}}">{{post.newsgroup.name}}</a></div>
  <div class="post-header">
    <div class="post-cite"><a href="{{post.get_absolute_url}}">&gt;&gt;{{post.shorthash}}</a></div>
    <div class="post-info">
      <div class="post-name">{{post.name}}</div>
      <div class="post-subject">{{post.subject}}</div>
      <div class="post-date">{{post.postdate|date}}</div>
    </div>
  </div>

  <div class="attachments">
    {% for a in post.attachments.all %}
    <a target="_blank" href="{{a.source}}"><img class="thumb" src="{{a.thumb}}"></img></a>
    {% endfor %}
  </div>
  <pre class="postbody">{{post.message | truncate | memepost }}</pre>
</div>
{% endfor %}
</div>
{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/keygen.html
{% extends "frontend/base.html" %}
{% block title %} new tripcode keypair {% endblock %}
{% block content %}
<pre class="tripcode-outer">public key: {{pk}}
secret key: {{sk}}
</pre>
{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/mod.html
{% extends "frontend/base.html" %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/modlogin.html
{% extends "frontend/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<label for="secret"> secret key </label>
	<input type="password" id="secret" name="secret"></input>
	<input type="hidden" name="action" value="login"></input>
	<input type="submit" value="login"></input>
</form>
{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/modpage.html
{% extends "frontend/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<input type="hidden" name="action" value="logout"></input>
	<input type="submit" value="logout"></input>
</form>
<form method="POST">
	{% csrf_token %}
	<input type="hidden" name="action" value="delete"></input>
	<label for="bulk-delete"> bulk delete</label>
	<textarea name="posts"></textarea>
	<input type="submit" value="delete"></input>
</form>


{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/postform.html
{% load captcha %}
<div class="postform_outer">
  <form id="postform" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="postform">
       <tbody>
         <tr>
           <th>
             Name
           </th>
           <td>
             <span>
               <input type="text" name="name" value="" id="postform_name" />
               <span id="postform_msg"></span>
             </span>
           </td>
         </tr>
         <tr>
           <th>
             Subject
           </th>
           <td>
             <input type="text" name="subject" value="" id="postform_subject" />
             <input type="submit" value="{{button}}" class="button" id="postform_submit" />
           </td>
         </tr>
         <tr>
           <th>
             Message
           </th>
           <td>
             <textarea id="postform_message" name="message"></textarea>
           </td>
         </tr>
           <tr>
             <th>
           </th>
           <td>
             <input class="postform_attachment" id="postform_attachments" type="file" name="attachment" multiple />
           </td>
           </tr>
         <tr>
           <th>
             Captcha
           </th>
           <td>
             <img id="captcha_img" src="{{ captcha }}" alt="captcha" />
           </td>
         </tr>
         <tr>
           <th>
             Solution
           </th>
           <td>
             <input type="text" name="captcha" autocomplete="off" id="captcha_solution" height="175" width="350"/>
           </td>
         </tr>
         <tr>
           <th>
             <label id="censor-toggle" for="censor-tools">[censor tools]</label>
           </th>
           <td>
             <input type="checkbox" id="censor-tools"><div style="display: none;">
               <table>
                 <tbody>
                   <tr>
                     <th>
                       Actions:
                     </th>
                     <td>
                       <textarea cols=85 name="modactions" id="modactions"></textarea>
                     </td>
                   </tr>
                   <tr>
                     <th>
                       Secret:
                     </th>
                     <td>
                       <input type="password" name="secret"></input>
                     </td>
                   </tr>
                   <tr>
                     <th>
                       <button onclick="document.getElementById('postform').submit()">report</button>
                     </th>
                     <td>
                     </td>
                   </tr>
                 </tbody>
               </table>
             </div>
           </td>
         </tr>
       </tbody>
     </table>

  </form>
</div>

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/postresult.html
{% extends "frontend/base.html" %}
{% block head %}
<meta http-equiv="refresh" content="2; {{refresh_url}}"></meta>
{% endblock %}

{% block content %}

{% if error %}
<pre class="error"> failed to post: {{error}} </pre>
{% else %}
<pre class="posted"> posted </pre>
{% endif %}

{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/redirect.html
{% extends "frontend/base.html" %}
{% block head %}
<meta http-equiv="refresh" content="1; {{url}}" />
{% endblock %}
{% block content %}
<pre>{{msg}}</pre>
{% endblock %}

contrib/frontends/django/nntpchan/nntpchan/templates/frontend/thread.html
{% extends "frontend/base.html" %}
{% load chanup %}
{% block title %} {{op.subject}} {% endblock %}
{% block navbar_links %}
<div class="navbar_link"><a href="{{op.newsgroup.get_absolute_url}}">back to {{op.newsgroup.name}}</a></div>
{% endblock %}
{% block content %}
{% include "frontend/postform.html" %}
<div id="{{op.posthash}}" class="thread">
  <div class="post op" data-msgid="{{op.msgid}}">
    <div class="post-header">
      <div class="post-reply"><a href="{{op.get_absolute_url}}">[reply]</a></div>
      <div class="post-cite" onclick="thread_citepost('{{op.posthash}}')">&gt;&gt;{{op.shorthash}}</div>
      <div class="post-info">
        <div class="post-report">
        <label for="report_{{op.posthash}}">[x]</label>
          <input type="checkbox" id="report_{{op.posthash}}">
          <div style="display: none;" onclick="nntpchan_report_thread('{{op.posthash}}')">
            <div class="mod-delete">
              [delete thread]
            </div>
          </div>
        </div>
        <div class="post-name">{{op.name}}</div>
        <div class="post-subject">{{op.subject}}</div>
        <div class="post-date">{{op.postdate|date}}</div>
      </div>
    </div>
    <div class="attachments">
      {% for a in op.attachments.all %}
      <a target="_blank" href="{{a.source}}"><img class="thumb" src="{{a.thumb}}"></img></a>
      {% endfor %}
    </div>
    <pre class="postbody">{{op.message|memepost}}</pre>
  </div>
  {% for reply in op.get_all_replies %}
  <div class="post reply" data-msgid="{{reply.msgid}}" id="{{reply.posthash}}">
    <div class="post-header">
      <div class="post-reply"><a href="{{reply.get_absolute_url}}">[reply]</a></div>
      <div class="post-cite" onclick="thread_citepost('{{reply.posthash}}')">&gt;&gt;{{reply.shorthash}}</div>
      <div class="post-info">
        <div class="post-report">
        <label for="report_{{reply.posthash}}">[x]</label>
          <input type="checkbox" id="report_{{reply.posthash}}">
          <div style="display: none;" onclick="nntpchan_report('{{reply.msgid}}')">
            <div class="mod-delete">
              [delete post]
            </div>
          </div>
        </div>
        <div class="post-name">{{reply.name}}</div>
        <div class="post-subject">{{reply.subject}}</div>
        <div class="post-date">{{reply.postdate|date}}</div>
      </div>
    </div>
    <div class="attachments">
      {% for a in reply.attachments.all %}
      <a target="_blank" href="{{a.source}}"><img class="thumb" src="{{a.thumb}}"></img></a>
      {% endfor %}
    </div>
    {% autoescape off %}
    <pre class="postbody">{{reply.message|memepost}}</pre>
    {% endautoescape %}
  </div>
  {% endfor %}
</div>
<hr />
{% endblock %}